// Code generated by "stringer -trimprefix St_ -type=statementIndexType"; DO NOT EDIT.

package basesql

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[St_nntp_article_exists_or_banned_by_msgid-0]
	_ = x[St_nntp_article_valid_by_msgid-1]
	_ = x[St_nntp_article_num_by_msgid-2]
	_ = x[St_nntp_article_msgid_by_num-3]
	_ = x[St_nntp_article_get_gpid-4]
	_ = x[St_nntp_select-5]
	_ = x[St_nntp_select_and_list-6]
	_ = x[St_nntp_next-7]
	_ = x[St_nntp_last-8]
	_ = x[St_nntp_newnews_all-9]
	_ = x[St_nntp_newnews_one-10]
	_ = x[St_nntp_newnews_all_group-11]
	_ = x[St_nntp_newgroups-12]
	_ = x[St_nntp_listactive_all-13]
	_ = x[St_nntp_listactive_one-14]
	_ = x[St_nntp_over_msgid-15]
	_ = x[St_nntp_over_range-16]
	_ = x[St_nntp_over_curr-17]
	_ = x[St_nntp_hdr_msgid_msgid-18]
	_ = x[St_nntp_hdr_msgid_subject-19]
	_ = x[St_nntp_hdr_msgid_any-20]
	_ = x[St_nntp_hdr_range_msgid-21]
	_ = x[St_nntp_hdr_range_subject-22]
	_ = x[St_nntp_hdr_range_any-23]
	_ = x[St_nntp_hdr_curr_msgid-24]
	_ = x[St_nntp_hdr_curr_subject-25]
	_ = x[St_nntp_hdr_curr_any-26]
	_ = x[St_web_listboards-27]
	_ = x[St_web_thread_list_page-28]
	_ = x[St_web_overboard_page-29]
	_ = x[St_web_thread_catalog-30]
	_ = x[St_web_overboard_catalog-31]
	_ = x[St_web_thread-32]
	_ = x[St_web_prepost_newthread-33]
	_ = x[St_web_prepost_newpost-34]
	_ = x[St_post_newthread_sb_nf-35]
	_ = x[St_post_newthread_mb_nf-36]
	_ = x[St_post_newthread_sb_sf-37]
	_ = x[St_post_newthread_mb_sf-38]
	_ = x[St_post_newthread_sb_mf-39]
	_ = x[St_post_newthread_mb_mf-40]
	_ = x[St_post_newreply_sb_nf-41]
	_ = x[St_post_newreply_mb_nf-42]
	_ = x[St_post_newreply_sb_sf-43]
	_ = x[St_post_newreply_mb_sf-44]
	_ = x[St_post_newreply_sb_mf-45]
	_ = x[St_post_newreply_mb_mf-46]
	_ = x[St_mod_ref_write-47]
	_ = x[St_mod_ref_find_post-48]
	_ = x[St_mod_update_bpost_activ_refs-49]
	_ = x[St_mod_autoregister_mod-50]
	_ = x[St_mod_delete_by_msgid-51]
	_ = x[St_mod_ban_by_msgid-52]
	_ = x[St_mod_bname_topts_by_tid-53]
	_ = x[St_mod_refresh_bump_by_tid-54]
	_ = x[St_mod_set_mod_priv-55]
	_ = x[St_mod_set_mod_priv_group-56]
	_ = x[St_mod_unset_mod-57]
	_ = x[St_mod_fetch_and_clear_mod_msgs_start-58]
	_ = x[St_mod_fetch_and_clear_mod_msgs_continue-59]
	_ = x[St_mod_load_files-60]
	_ = x[St_mod_check_article_for_push-61]
	_ = x[St_mod_delete_ph_for_push-62]
	_ = x[St_mod_add_ph_after_push-63]
	_ = x[St_mod_joblist_modlist_changes_get-64]
	_ = x[St_mod_joblist_modlist_changes_set-65]
	_ = x[St_mod_joblist_modlist_changes_del-66]
	_ = x[St_mod_joblist_refs_deps_recalc_get-67]
	_ = x[St_mod_joblist_refs_deps_recalc_set-68]
	_ = x[St_mod_joblist_refs_deps_recalc_del-69]
	_ = x[St_mod_joblist_refs_recalc_get-70]
	_ = x[St_puller_get_last_newnews-71]
	_ = x[St_puller_set_last_newnews-72]
	_ = x[St_puller_get_last_newsgroups-73]
	_ = x[St_puller_set_last_newsgroups-74]
	_ = x[St_puller_get_group_id-75]
	_ = x[St_puller_set_group_id-76]
	_ = x[St_puller_unset_group_id-77]
	_ = x[St_puller_load_temp_groups-78]
}

const _statementIndexType_name = "nntp_article_exists_or_banned_by_msgidnntp_article_valid_by_msgidnntp_article_num_by_msgidnntp_article_msgid_by_numnntp_article_get_gpidnntp_selectnntp_select_and_listnntp_nextnntp_lastnntp_newnews_allnntp_newnews_onenntp_newnews_all_groupnntp_newgroupsnntp_listactive_allnntp_listactive_onenntp_over_msgidnntp_over_rangenntp_over_currnntp_hdr_msgid_msgidnntp_hdr_msgid_subjectnntp_hdr_msgid_anynntp_hdr_range_msgidnntp_hdr_range_subjectnntp_hdr_range_anynntp_hdr_curr_msgidnntp_hdr_curr_subjectnntp_hdr_curr_anyweb_listboardsweb_thread_list_pageweb_overboard_pageweb_thread_catalogweb_overboard_catalogweb_threadweb_prepost_newthreadweb_prepost_newpostpost_newthread_sb_nfpost_newthread_mb_nfpost_newthread_sb_sfpost_newthread_mb_sfpost_newthread_sb_mfpost_newthread_mb_mfpost_newreply_sb_nfpost_newreply_mb_nfpost_newreply_sb_sfpost_newreply_mb_sfpost_newreply_sb_mfpost_newreply_mb_mfmod_ref_writemod_ref_find_postmod_update_bpost_activ_refsmod_autoregister_modmod_delete_by_msgidmod_ban_by_msgidmod_bname_topts_by_tidmod_refresh_bump_by_tidmod_set_mod_privmod_set_mod_priv_groupmod_unset_modmod_fetch_and_clear_mod_msgs_startmod_fetch_and_clear_mod_msgs_continuemod_load_filesmod_check_article_for_pushmod_delete_ph_for_pushmod_add_ph_after_pushmod_joblist_modlist_changes_getmod_joblist_modlist_changes_setmod_joblist_modlist_changes_delmod_joblist_refs_deps_recalc_getmod_joblist_refs_deps_recalc_setmod_joblist_refs_deps_recalc_delmod_joblist_refs_recalc_getpuller_get_last_newnewspuller_set_last_newnewspuller_get_last_newsgroupspuller_set_last_newsgroupspuller_get_group_idpuller_set_group_idpuller_unset_group_idpuller_load_temp_groups"

var _statementIndexType_index = [...]uint16{0, 38, 65, 90, 115, 136, 147, 167, 176, 185, 201, 217, 239, 253, 272, 291, 306, 321, 335, 355, 377, 395, 415, 437, 455, 474, 495, 512, 526, 546, 564, 582, 603, 613, 634, 653, 673, 693, 713, 733, 753, 773, 792, 811, 830, 849, 868, 887, 900, 917, 944, 964, 983, 999, 1021, 1044, 1060, 1082, 1095, 1129, 1166, 1180, 1206, 1228, 1249, 1280, 1311, 1342, 1374, 1406, 1438, 1465, 1488, 1511, 1537, 1563, 1582, 1601, 1622, 1645}

func (i statementIndexType) String() string {
	if i < 0 || i >= statementIndexType(len(_statementIndexType_index)-1) {
		return "statementIndexType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _statementIndexType_name[_statementIndexType_index[i]:_statementIndexType_index[i+1]]
}
